model:
  name: 'SciBERTClassifier'
  num_labels: 6
  pretrained_model: 'allenai/scibert_scivocab_uncased'
  save_path: 'bert_classifier.pth'

training:
  batch_size: 16
  num_epochs: 3
  learning_rate: 2e-5
  max_grad_norm: 1.0

data:
  max_length: 64
  test_size: 0.2